# Generated by Django 5.2 on 2026-02-21 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caregivers', '0001_initial'),
        ('patients', '0002_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('report_description', models.TextField(blank=True, null=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_reports', to='caregivers.caregiver')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_reports', to='patients.patient')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_reports', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Shift Report',
                'verbose_name_plural': 'Shift Reports',
                'db_table': 'shift_report',
            },
        ),
    ]
