# Generated by Django 5.2 on 2026-02-28 00:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftreport',
            old_name='report_description',
            new_name='important_notes',
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_reports', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='patient_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='status',
            field=models.CharField(default='Scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='tasks_performed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
