# Generated by Django 5.2 on 2026-02-24 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caregivers', '0001_initial'),
        ('patients', '0002_initial'),
        ('users', '0003_remove_payment_caregiver_remove_shiftreport_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('care_type', models.CharField(choices=[('FullTime', 'Tiempo Completo'), ('PartTime', 'Medio Tiempo'), ('Hourly', 'Por Horas'), ('LiveIn', 'Cama Adentro'), ('Overnight', 'Nocturno')], default='FullTime', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Activa'), ('Completed', 'Finalizada'), ('Cancelled', 'Cancelada'), ('OnHold', 'En Pausa')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, db_column='assigned_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to='users.admin')),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='caregivers.caregiver')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'db_table': 'assignments',
                'ordering': ['-start_date'],
            },
        ),
    ]
