# Generated by Django 5.2 on 2026-02-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='period_end',
            field=models.DateField(blank=True, help_text='Fin del período de pago', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='period_start',
            field=models.DateField(blank=True, help_text='Inicio del período de pago', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pendiente'), ('Success', 'Exitoso'), ('Failed', 'Fallido')], default='Pending', max_length=20),
        ),
    ]
