# Generated by Django 5.2 on 2026-02-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='caregiver',
        ),
        migrations.RemoveField(
            model_name='shiftreport',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='shiftreport',
            name='caregiver',
        ),
        migrations.RemoveField(
            model_name='shiftreport',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='ShiftReport',
        ),
    ]
